server:
  port: 9999
spring:
  application:
    name: C-Gateway
  redis:
    host: 192.168.46.128
    port: 6379
    database: 0
    password: wereiyou123
    jedis:
      pool:
        max-active: 20
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.46.128:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: C-Auth
          uri: lb://C-Auth
          predicates:
            - Path=/oauth/**
        - id: im-user
          uri: lb://im-user
          predicates:
            - Path=/auth/**
        - id: id-generator
          uri: lb://id-generator
          predicates:
            - Path=/id/**
        - id: im-file
          uri: lb://im-file
          predicates:
            - Path=/image/**
            - Path=/file/**
        - id: im-web
          uri: lb://im-web
          predicates:
            - Path=/friend/**
            - Path=/chat/**
            - Path=/user/**
            - Path=/group/**
        - id: im-netty
          uri: lb:ws://im-netty
          predicates:
            - Path=/ws/**
whitelist:
  paths:
    - /auth/login
    - /auth/register
    - /oauth/*